### PR TITLE
Upgrade github.com/container-storage-interface/spec

### LINKED ISSUE #795: Upgrade errors for container-storage-interface
/kind bug

**What happened?**
Upgrading container-storage-interface introduces compilation issues: 
See https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/pull/707 CI failures

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**
`go get github.com/container-storage-interface/spec`

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

### PR DESCRIPTION
**Pull request by yussufsh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Resolves errors shown in #707

After the upgrade, there were many govet errors related to the change. Fixed the errors in a separate commit but included in the same PR to allow the CI to merge the changes.
PFA [build-log.txt](https://github.com/user-attachments/files/18134344/build-log.txt) for go vet issues. The errors are related to `copies lock value` of structs using Mutex. Instead, we will use references.

**Which issue(s) this PR fixes**:

Fixes #795

**Special notes for your reviewer**:
With the new upgrade there were compilation errors which had to be fixed manually.

**Release note**:
```
none
```

### CODE REVIEW

**Review by mkumatag — CHANGES_REQUESTED** [review]
can you please split this PR into 2? one for upgrade and another for vet issues with new GitHub issue created with all the details

**Comment by yussufsh** [comment]
> can you please split this PR into 2? one for upgrade and another for vet issues with new GitHub issue created with all the details

The vet issues won't allow the upgrade PR to be merged because of verify target failures. That is why I have added two different commits for easy review. Let me know if you still think otherwise.

**Comment by mkumatag** [comment]
> > can you please split this PR into 2? one for upgrade and another for vet issues with new GitHub issue created with all the details
> 
> The vet issues won't allow the upgrade PR to be merged because of verify target failures. That is why I have added two different commits for easy review. Let me know if you still think otherwise.

okay, please add more information in the description about the errors and the reason,

**Comment by yussufsh** [comment]
> > > can you please split this PR into 2? one for upgrade and another for vet issues with new GitHub issue created with all the details
> > 
> > 
> > The vet issues won't allow the upgrade PR to be merged because of verify target failures. That is why I have added two different commits for easy review. Let me know if you still think otherwise.
> 
> okay, please add more information in the description or in the GitHub issue about the errors and the reason

Added more text in the description.

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
